cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace="cart")),
    path('orders/',include('orders.urls',namespace='orders')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('',include('shop.urls',namespace="shop")),
    
]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name='orders'
urlpatterns = [
    path('create/',views.create_order,name="create"),
    
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'
urlpatterns = [
    path('',views.ProductList,name="product_list"),
    path('<slug:category_slug>/',views.ProductList,name="product_list_by_category"),
    path('<int:id>/<slug:slug>/',views.ProductDetail,name="product_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QANTITY_CHOICES=[(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity=forms.TypedChoiceField(choices=PRODUCT_QANTITY_CHOICES,coerce=int)
    override=forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from shop.models import Product
from django.views.decorators.http import require_POST
from .forms import CartAddProductForm
from .cart import Cart
import json
from django.core.serializers.json import DjangoJSONEncoder
@require_POST
def cart_add(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    form=CartAddProductForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request,product_id):
    product=get_object_or_404(Product,pk=product_id)
    cart=Cart(request)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart=Cart(request)
    #context={'cart':json.dumps(cart,cls=DjangoJSONEncoder)}
    context={'cart':cart}
    return render(request,'cart/cart_detail.html',context)

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Your shopping cart{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'cart/cart_detail.css' %}">
<div class="cart">
<table>
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Qantity</th>
            <th>Remove</th>
            <th>Unit Price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td><a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="" width="50px" height="50px"></a></td>
            <td>{{product.name}}</td>
            <td>{{ item.quantity }}</td>
            <td><form action="{% url 'cart:cart_remove' product.id %}" method="POST">
               <input type="submit" value="Remove">
               {% csrf_token %}
            </form></td>
            <td>₹{{ item.price }}</td>
            <td>₹{{ item.total_price }}</td>
        </tr>
        

        {% endwith %}
        {% endfor %}
        <tr>
            <td>Total Price</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>₹{{cart.get_total_price}}</td>
        </tr>
    </tbody>
</table>

<p id="check" style="float:right">
    <a href="{% url 'shop:product_list' %}" id="continue-shopping">Continue shopping</a>
    <a href="{% url 'orders:create' %}" id="checkout">PROCEED</a>
</p>
</div>

{% endblock %}