cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace="cart")),
    path('orders/',include('orders.urls',namespace='orders')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('',include('shop.urls',namespace="shop")),
    
]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'
urlpatterns = [
    path('',views.ProductList,name="product_list"),
    path('<slug:category_slug>/',views.ProductList,name="product_list_by_category"),
    path('<int:id>/<slug:slug>/',views.ProductDetail,name="product_detail"),
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering=['name']
        indexes=[models.Index(fields=['name'])]
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    
class Product(models.Model):
    category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    slug=models.SlugField(max_length=200,unique=True)
    image=models.ImageField(upload_to='products/%y/%m/%d/',blank=True)
    description=models.TextField(max_length=500)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
         ordering=['name']
         indexes=[
                models.Index(fields=['id','slug']),
                models.Index(fields=['name']),
                models.Index(fields=['-created'])  
                  ]
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id,self.slug])

shop/views.py
from django.shortcuts import render
from .models import Product,Category
from django.shortcuts import get_object_or_404
from cart.forms import CartAddProductForm

def ProductList(request,category_slug=None):
    categories=Category.objects.all()
    category=None
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        products=Product.objects.filter(category=category)
    else:
        products=Product.objects.all()
    context={"products":products,'categories':categories,'category':category}
    return render(request,'shop/ProductList.html',context)

def ProductDetail(request,id,slug):
    product=get_object_or_404(Product,pk=id,slug=slug)
    cart_add_product_form=CartAddProductForm()
    context={'product':product,'cart_add_product_form':cart_add_product_form }
    return render(request,'shop/ProductDetail.html',context)

shop/templates/shop/ProductDetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{product.name}}{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'shop/ProductDetail.css' %}">
<div class="detail">
    <div style="float:left" id="image">
        <img src="{{product.image.url}}" alt="" height="500px" width="300px">
        <form action="{% url 'cart:cart_add' product.id %}" method='post'>
            {{cart_add_product_form}}
            <input type="submit" value='Add to Cart' id="submit">
            {% csrf_token %}
        </form>
    </div>
    <div id="description">
        <h1>{{product.name}}</h1>
        <h2>₹{{product.price}}</h2>
        <p>{{product.description |linebreaks}}</p>
        

    </div> 

</div>

{% endblock %}

shop/templates/shop/ProductList.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'shop/ProductList.css' %}">

<div id="sidebar">
    <ul>
        <h2>Categories</h2>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">All</a>
        </li>
        {% for ctgry in categories %}
        <li>
            <a   href="{{ ctgry.get_absolute_url }}">{{ctgry.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div id="product-list">

    <div >
        {% if category %}{{category.name}}{% endif %}

    </div>
    <div>
        {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}"><img src="{{product.image.url}}" alt="" widht="150px"
                    height="200px"></a><br>
            <a id="product-name" href="{{ product.get_absolute_url }}">{{product.name}}</a>
            <p id="price">₹{{product.price}}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}