cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.cart_add,name="cart_add"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace="cart")),
    path('orders/',include('orders.urls',namespace='orders')),
    path('payment/',include('payment.urls',namespace='payment')),
    path('',include('shop.urls',namespace="shop")),
    
]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from  . import views 

app_name='payment'
urlpatterns = [
    path('process/',views.payment_process,name="process"),
    path('completed/',views.payment_completed,name='completed'),
    path('canceled/',views.payment_canceled,name='canceled'),
    path('confirm/',views.OrderConfirmed,name='confirm'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render,get_object_or_404,reverse,redirect
from decimal import Decimal
import stripe
from django.conf import settings
from orders.models import Order
from orders.forms import OrderCreateForm
from cart.cart import Cart
from orders.tasks import order_created
stripe.api_key=settings.STRIPE_SECRET_KEY

def payment_process(request):
    order_id=request.session['order_id']
    order=get_object_or_404(Order,id=order_id)
    if request.method=='POST':
        cancel_url=request.build_absolute_uri(reverse('payment:canceled'))
        success_url=request.build_absolute_uri(reverse('payment:completed'))
        session_data={
            'success_url':success_url,
            'cancel_url':cancel_url,
            'mode':'payment',
            'client_reference_id':order.id,
            'line_items':[]
            }
        
        for item in order.items.all():
            session_data['line_items'].append({
            'price_data':{
                'unit_amount':int(item.price)*Decimal('100'),
                'currency':'INR',
            'product_data':{
                'name':item.product.name}
            },
            'quantity':item.quantity
            }),
        session=stripe.checkout.Session.create(**session_data)
        return redirect(session.url,code=303)
    else:
        return render(request,'payment/process.html',locals())
def payment_completed(request):
    order_id=request.session['order_id']
    order=Order.objects.get(id=order_id)
    order.paid=True
    order.save()
    cart=Cart(request)
    #cart.clear()
    order_created(order.id)
    return render(request,'payment/completed.html',{'order_id':order_id,'order':order})
def payment_canceled(request):
    return render(request,'payment/canceled.html')

def OrderConfirmed(request):
    order_id=request.session['order_id']
    order=Order.objects.get(id=order_id)
    order_created(order.id)
    return render(request,'payment/confirm.html',{'order_id':order_id,'order':order})

payment/templates/payment/canceled.html
{% extends "base.html" %}
{% block title %}Payment canceled{% endblock %}
{% block content %}
 <h1>Your payment has not been processed</h1>
 <p>There was a problem processing your payment.</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Payment successful{% endblock %}
{% block content %}
 <h1>Your payment was successful</h1>

 <p>Your payment has been processed successfully.</p>
 
{% endblock %}

payment/templates/payment/confirm.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Payment successful{% endblock %}
{% block content %}
 <h1>Your Order has been successful</h1>
 <p>Your order id is {{order.id}}</p>
<p>Order related information has sent to your email </p>
 
{% endblock %}

payment/templates/payment/process.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Payment{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'payment/process.css' %}">
<div>
    <h1>Order Summary</h1>
    <table>
        <tr>
            <td>Image</td>
            <td>Product</td>
            <td>Price</td>
            <td>Quantity</td>
            <td>Total</td>
        </tr>
        {% for item in order.items.all %}
        <tr>
            <td><img src="{{item.product.image.url}}" height="100px" width="100px"></td>
            <td>{{item.product.name}}</td>
            <td>{{item.price}}</td>
            <td>{{item.quantity}}</td>
            <td>₹{{item.get_cost }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td>Total </td>
            <td></td>
            <td></td>
            <td></td>
            <td><b>₹{{order.get_total_cost }}</b></td>
        </tr>
    </table>
    <h2>Select a payment method</h2>
    <ul>
        
        <form action="{% url 'payment:confirm' %}" method="POST">
            <input type="submit" value="Cash on Delivery" id="confirm">
            {% csrf_token %}
        </form>
        
        
        <form action="{% url 'payment:process' %}" method="POST">
            <input type="submit" value="Pay by Card" id="paynow">
            {% csrf_token %}
        </form>
        
    </ul>
    
    
</div>
{% endblock %}